### ISSUE TITLE
Linking to Dev Meeting Logs

### ISSUE THREAD

**Issue by Ryuno-Ki** [Halium/halium.org#13]
Core developers are meeting regularly and providing summaries of what they talked about/agreed upon.

Should we link them?

In case it is a gist, should we transform the link into an iframe using JavaScript?

**Comment by bhush9** [comment]
I think it makes sense to write a blog post for "important" decisions taken during such meetings.. otherwise publishing "raw" meeting notes is not so informative.

Maybe from next week we can publish blog post on blog.. but for now lets close this issue.
