### ISSUE TITLE
Create proper website

### ISSUE THREAD

**Issue by bhush9** [Halium/halium.org#7]
Currently @JBBgameich have started doing website, and we should improve it and push it here.

https://github.com/jbbgameich/halium-website

**Comment by JBBgameich** [comment]
I already solved a few issues: https://github.com/Halium/halium.org/issues/1 https://github.com/Halium/halium.org/issues/4 (will update this)

**Comment by mariogrip** [comment]
Can we close this?

**Comment by bhush9** [comment]
Yeah, lets close this, website is using "default" jekyll theme but that's another issue, we at least don't have flying logo currently. ;)
